[workspace]
authors = ["Yu-An Chen <atwood12@gmail.com>"]
channels = ["conda-forge"]
name = "pixi-env"
platforms = ["osx-arm64", "win-64", "linux-64"]
version = "0.1.0"

[tasks]
gui = "python run-ashlar.py --gui"
install-basicpy = "pixi install --locked --manifest-path basicpy-env/pixi.toml"
setup-basicpy = "pixi run --manifest-path basicpy-env/pixi.toml setup-basicpy"

[dependencies]
python = "3.10.*"
pip = ">=25.2,<26"
openjdk = ">=21,<22"
pyqt = ">=5.15.11,<6"
asciitree = ">=0.3.3,<0.4"

[target.win-64.dependencies]
pyjnius = ">=1.6.1,<2"

[target.win-64.pypi-dependencies]
pywin32 = ">=311, <312"

[target.linux-64.dependencies]
pyjnius = ">=1.6.1,<2"

[pypi-dependencies]
ashlar = { git = "https://github.com/Yu-AnChen/ashlar.git", rev = "d7b948be8f24b6d7d81bfbb2f8d9b256d64456f8" }
palom = ">=2025.7"
diplib = ">=3.4.1, <4"
